### ISSUE TITLE
Guidance to make disk volume to be visible inside a mlc container.

### ISSUE THREAD

**Issue by sreenivasaupadhyaya** [aime-team/aime-ml-containers#1]
I use AIME server with two 2TB storage volumes. 
When i do a "df -h" command i see the the two 2TB storage volumes and I am able to access them from the terminal.
However, when inside a mlc-container i only can see and access the one 2TB storage volume on which the system is installed.

IT would be great if there is a way to access (or mount) the second 2 TB storage in the mlc-container.

Thanks!

**Comment by sreenivasaupadhyaya** [comment]
mlc-create container_name framework version [-w=workspace_dir] [-d=data_dir]

**Comment by kinred** [comment]
With the -d option of mlc-create one can specify a data directory on another drive. The specified directory is then accessible as /data within the container

**Comment by sreenivasaupadhyaya** [comment]
@kinred 
Could you please tell me if this is possible
#5
