### ISSUE TITLE
Create container with Specific GPU id?

### ISSUE THREAD

**Issue by ethereor** [aime-team/aime-ml-containers#2]
I can't find a way to create a container with a specific GPU, mlc-create appears to use the default 'all' value in all cases - Is there a way to create a container for GPU 0 and one for GPU 1 when there are two GPUs available?

**Comment by kinred** [comment]
Thank you for your input. Currently this feature is not available yet, but we will try to incorporate it in the next update.

A workaround would be to set/export the "CUDA_VISIBLE_DEVICES" variable inside the container.

**Comment by ethereor** [comment]
Ok perfect, I will work with CUDA_VISIBLE_DEVICES instead, thanks for the quick reply!
