### ISSUE TITLE
Support for including multiple mount directories in mlc container.

### ISSUE THREAD

**Issue by sreenivasaupadhyaya** [aime-team/aime-ml-containers#5]
Hi @kinred ,

Original docker container allows the support for multiple data mounts while creating. 
1. Do we have the same functionality in mlc containers>?
2. if not can we modify the mlc-containers to add this functionality?

For eg:  i want something like this
"mlc-create test_data Tensorflow 2.3.1-nvidia -d=/mnt/data1 -d=/mnt/data2"

**Comment by kinred** [comment]
The MLC idea is to have a single mount point for data, this is to make MLC containers with future extensions to be exchangable and exportable. Maybe the single data directory can be already be setup in the OS through symbolic links or similair mechanisms?

But we will add the feature to mount multiple data directories as feature request.

**Comment by sreenivasaupadhyaya** [comment]
@kinred  thank you for the suggestion. I am able to use single one.

"But we will add the feature to mount multiple data directories as feature request." - that would be nice to have.
