### ISSUE TITLE
Unable to update mlc container to get latest support for tensorflow 2.12.0 as seen in the description.

### ISSUE THREAD

**Issue by sreenivasaupadhyaya** [aime-team/aime-ml-containers#7]
Hi @kinred ,

I tried to update the MLC container, more info in the screen shot. However, I was not able to get the support for latest tensorflow version.

![image](https://github.com/aime-team/aime-ml-containers/assets/7950974/69468d68-a368-420f-a80e-5bf0daa36790)

Can it be due to the fact that the current installation of MLC container  (default installation) is from a branch and not from the master? Could you guide me to upate the mlc or check what the current version installed is.

Thanks and regards,
Srini

**Comment by makjaveli** [comment]
Hi @sreenivasaupadhyaya,

The Ubuntu 18.04 Pascal GPU branch of AIME MLC is not updated anymore. Please switch to the Ampere branch of MLC by executing following command:

cd /opt/aime-ml-containers
sudo git checkout -b stable-cuda-ampere
sudo git pull origin stable-cuda-ampere

The Ampere branch has the latest Tensorflow and Pytorch containers. Probably a CUDA update to CUDA-11-7 is required to use all containers.

Best regards

**Comment by sreenivasaupadhyaya** [comment]
@kinred thanks for the swift reply

I got the below while trying to execute the commands

![image](https://github.com/aime-team/aime-ml-containers/assets/7950974/668cb7f1-f5e4-491b-8dea-aac692c24058)

Looks like there are some conflicts, what could i do now?

**Comment by sreenivasaupadhyaya** [comment]
Also, could you please give me the command for the CUDA update as you mentioned above.

Thanks for understanding and your time.

Regards,
Sreenivasa

**Comment by makjaveli** [comment]
> @kinred thanks for the swift reply
> 
> I got the below while trying to execute the commands
> 
> ![image](https://user-images.githubusercontent.com/7950974/261613481-668cb7f1-f5e4-491b-8dea-aac692c24058.png)
> 
> Looks like there are some conflicts, what could i do now?

It is probably easier to do a clean clone of the correct branch. So please do:

sudo mv /opt/aime-ml-containers /opt/aime-ml-containers.bak
sudo git clone https://github.com/aime-team/aime-ml-containers.git /opt/aime-ml-containers --branch stable-cuda-ampere

**Comment by sreenivasaupadhyaya** [comment]
@makjaveli  thanks for the reply.
I created the MLC container. However, the 2.12.0 based container cannot find the GPUs in tensorflow.
Overall, looks like the tensorflow is not able to find the cuda modules.

Please find my snippet below copied from terminal on the mlc containerr DL container2 based on tf 2.12.0

> "[DL-container3] root@SERV-2006-000010:/workspace$ python
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.python.client import device_lib
2023-09-15 10:57:10.762668: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>> device_lib.list_local_devices()
2023-09-15 10:57:19.152230: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE: forward compatibility was attempted on non supported HW
2023-09-15 10:57:19.152306: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:168] retrieving CUDA diagnostic information for host: SERV-2006-000010
2023-09-15 10:57:19.152323: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:175] hostname: SERV-2006-000010
2023-09-15 10:57:19.152496: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:199] libcuda reported version is: NOT_FOUND: was unable to find libcuda.so DSO loaded into this program
2023-09-15 10:57:19.152549: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:203] kernel reported version is: 510.108.3
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 4260850405592754492
xla_global_id: -1"


The same commands do find tthe GPU in my other mlc containers based on tf 2.3.x

Question: Could you please check if you can replicate this and help me fix the driver dependency?

**Comment by kinred** [comment]
Please run following commands:

sudo apt list --installed | grep cuda-1

sudo apt-mark showhold

And send the results to support@aime.info . We will check them and send individual instructions what could be done.

**Comment by kinred** [comment]
This is not a general MLC issue.

**Comment by kinred** [comment]
This is not a general MLC issue.

**Comment by sreenivasaupadhyaya** [comment]
@kinred  Thanks and done,
